[tool.poetry]
name = "laplace-torch"
version = "0.1a2"
description = "laplace - Laplace approximations for deep learning"
authors = ["Alex Immer"]
license = "MIT"
readme = "README.md"
packages = [{include = "laplace"}]

[[tool.poetry.source]]
name = "github"
url = "https://github.com/AlexImmer/Laplace"

[tool.poetry.dependencies]
python = ">=3.8.0,<4"
backpack-for-pytorch = "^1.5.2"
torchaudio = "<2.0.2"
asdfghjkl = "^0.1a2"
matplotlib = "^3.7.1"
netcal = "^1.3.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pdoc3 = "^0.10.0"
cython = "^0.29.34"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"